### ISSUE TITLE
Error messages from sudo command is outputted into the file

### ISSUE THREAD

**Issue by saki7** [Shougo/unite-sudo#1]
For example, when you entered a wrong password:

The file to open:

```
lorem ipsum
```

Becomes:

```
Sorry, try again. # <-- this is the `sudo` command's error message

lorem ipsum
```

**Comment by Shougo** [comment]
Sorry, Please update vimproc.

**Comment by saki7** [comment]
Are you really sure that:
Shougo/vimproc@6733cbea34c4b673c265d21de8bfe00a6942fdcf
this commit fixed the issue?

I re-builded vimproc, but it doesn't take effect.
Maybe you forgot to include your changes in commit?

**Comment by Shougo** [comment]
Sorry, I pushed it.

**Comment by saki7** [comment]
I checked the latest commit, but it still does not seem to fix the issue.

### My environment
- Ubuntu 12.04
- vim (w/ all patches)
- vimproc (head)

### Screenshots

**(first attempt: input wrong password)**
![unite-sudo-error-1](https://f.cloud.github.com/assets/1901813/348937/4bfc005a-9f98-11e2-866f-ee3864fa5a41.png)

**(second attempt: input correct password and file content is shown)**
![unite-sudo-error-2](https://f.cloud.github.com/assets/1901813/348938/4fd6813c-9f98-11e2-92fb-29520af5f38c.png)

Am I doing something wrong?

**Comment by Shougo** [comment]
Hmmm...
The behavior cannot be reappearred in my environment.
Is it worked sudo.vim?
http://www.vim.org/scripts/script.php?script_id=729

**Comment by Shougo** [comment]
And sudo is worked in vimshell?

**Comment by saki7** [comment]
I'm not using sudo.vim or vimshell. Unite and Unite-sudo only.
But, just now I installed vimshell and tried to open a file in the same way, `vim sudo:/etc/foo`, but it behaves in the same way either.

And I think, it was ok to use Unite-sudo in stand-alone. Unite-sudo only depends on Unite, vimproc, and vimfiler, right?

**Comment by Shougo** [comment]
> I'm not using sudo.vim or vimshell. Unite and Unite-sudo only.
> But, just now I installed vimshell and tried to open a file in the same way, vim sudo:/etc/foo, but it behaves in the same way either.

You must disable unite-sudo to use sudo.vim.

> And I think, it was ok to use Unite-sudo in stand-alone. Unite-sudo only depends on Unite, vimproc, and vimfiler, right?

Yes. But I want to know other plugins behavior in your environment.

**Comment by saki7** [comment]
Wait, I'm _not_ using sudo.vim.
I'm just opening the file with the `:e sudo:` prefix, isn't it the way to use it?

**Comment by saki7** [comment]
Referring to this post: http://lingr.com/room/vim/archives/2012/10/22#message-12588927

**Comment by Shougo** [comment]
> Wait, I'm not using sudo.vim.
> I'm just opening the file with the :e sudo: prefix, isn't it the way to use it?

Yes. But I want to know sudo.vim behavior in your environment.
Because, I may add option like sudo.vim behavior.

**Comment by saki7** [comment]
I see. I'll try sudo.vim.

**Comment by saki7** [comment]
I found that using `sudo.vim` results in the same behavior.
So maybe this is environment-specific, not Unite-sudo's problem.
But still, it would be very nice if Shougo san could fix this issue.

My sudo version:

```
$ sudo -V
Sudo version 1.8.3p1
Sudoers policy plugin version 1.8.3p1
Sudoers file grammar version 40
Sudoers I/O plugin version 1.8.3p1
```

I guess the `sudo` command outputs the error message into **stderr**, which is collected by Unite to the buffer. **Ignoring stderr** might fix the issue?

```
$ sudo cat /etc/nginx/mime.types >stdout.txt 2>stderr.txt
[sudo] password for saki7:  (input wrong password)
[sudo] password for saki7:  (correct password)
```

stdout.txt:

```
(file content)
```

stderr.txt:

```
Sorry, try again.
```

If further information needed, please ask me.

**Comment by Shougo** [comment]
Is it same behavior in vimshell?
Please execute below command.

`sudo cat {some_file}`

**Comment by saki7** [comment]
![Screenshot_from_2013-04-08 15:29:42](https://f.cloud.github.com/assets/1901813/350297/bde0398e-a015-11e2-99f4-c16db9389618.png)

The difference is that it becomes red. So it looks like vimshell handles stderr properly.

**Comment by Shougo** [comment]
Hmmm...
Why it works in vimshell only.
